# Node.js local development docker-compose file
services:
  # https://hub.docker.com/r/bitnami/postgresql
  postgres:
    container_name: ${DIR}_postgres_dev
    image: bitnami/postgresql:${POSTGRES_VER}.0
    volumes:
      - postgres_dev_data:/bitnami/postgresql
    tmpfs:
      - /docker-entrypoint-initdb.d
      - /docker-entrypoint-preinitdb.d
    env_file:
      - .env
    environment:
      POSTGRESQL_DATABASE: ${POSTGRES_DB} # database
      POSTGRESQL_USERNAME: ${POSTGRES_USER} # root
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD} # Passw0rd!
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Passw0rd!
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - ${POSTGRES_PORT}
  # https://hub.docker.com/r/bitnami/redis
  redis:
    container_name: ${DIR}_redis_dev
    image: bitnami/redis:${REDIS_VER}
    volumes:
      - redis_dev_data:/bitnami/redis/data
    env_file:
      - .env
    environment:
      ALLOW_EMPTY_PASSWORD: no
      REDIS_PASSWORD: ${REDIS_PASSWORD} # Passw0rd!
    ports:
      - ${REDIS_PORT}:6379
    expose:
      - ${REDIS_PORT}
volumes:
  postgres_dev_data: {}
  redis_dev_data: {}
